# Generated by Django 2.1.1 on 2019-03-01 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beds',
            fields=[
                ('idBeds', models.AutoField(primary_key=True, serialize=False)),
                ('bedNumber', models.IntegerField(default=0)),
                ('bedStatus', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('idDoctor', models.AutoField(primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=45)),
                ('middleName', models.CharField(max_length=45)),
                ('lastName', models.CharField(max_length=45)),
                ('contactNum', models.CharField(max_length=11)),
                ('username', models.CharField(max_length=45)),
                ('password', models.CharField(max_length=45)),
                ('rfid', models.CharField(max_length=30)),
                ('accountStatus', models.CharField(default='Active', max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('idEmployee', models.AutoField(primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=45)),
                ('middleName', models.CharField(max_length=45)),
                ('lastName', models.CharField(max_length=45)),
                ('contactNum', models.CharField(max_length=11)),
                ('username', models.CharField(max_length=45)),
                ('password', models.CharField(max_length=45)),
                ('usertype', models.CharField(max_length=45)),
                ('rfid', models.CharField(max_length=30, null=True)),
                ('accountStatus', models.CharField(default='Active', max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='HeartRate',
            fields=[
                ('idHeartRate', models.AutoField(primary_key=True, serialize=False)),
                ('heartRate', models.FloatField(default=0)),
                ('time', models.TimeField()),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='HeartRateEveryMinute',
            fields=[
                ('idHeartRate', models.AutoField(primary_key=True, serialize=False)),
                ('heartRate', models.FloatField(default=0)),
                ('time', models.TimeField()),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('idNews', models.AutoField(primary_key=True, serialize=False)),
                ('body', models.TextField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('idNotification', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('bedNumber', models.IntegerField()),
                ('body', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('idPatient', models.AutoField(primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=45)),
                ('middleName', models.CharField(max_length=45)),
                ('lastName', models.CharField(max_length=45)),
                ('birthDate', models.DateField()),
                ('minTemp', models.FloatField(default=0)),
                ('maxTemp', models.FloatField(default=0)),
                ('minHeartRate', models.IntegerField(default=0)),
                ('maxHeartRate', models.IntegerField(default=0)),
                ('contactperson', models.CharField(max_length=100, null=True)),
                ('contactNum', models.CharField(max_length=11)),
                ('status', models.CharField(max_length=45)),
                ('restrictions', models.CharField(default='false', max_length=20)),
                ('count', models.IntegerField(default=0)),
                ('bedNumber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unodosmattress.Beds')),
            ],
        ),
        migrations.CreateModel(
            name='Patient_Doctors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unodosmattress.Doctor')),
                ('Patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unodosmattress.Patient')),
            ],
        ),
        migrations.CreateModel(
            name='Patient_Table',
            fields=[
                ('idPatientTable', models.AutoField(primary_key=True, serialize=False)),
                ('idBeds', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unodosmattress.Beds')),
                ('idPatient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unodosmattress.Patient')),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('idPosition', models.AutoField(primary_key=True, serialize=False)),
                ('position', models.CharField(max_length=45)),
                ('time', models.TimeField()),
                ('date', models.DateField()),
                ('idPatient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unodosmattress.Patient')),
            ],
        ),
        migrations.CreateModel(
            name='Ref_Temp',
            fields=[
                ('idRef_Temp', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('minTemp', models.IntegerField(default=0)),
                ('maxTemp', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='RFID',
            fields=[
                ('idRFID', models.AutoField(primary_key=True, serialize=False)),
                ('RFIDnumber', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('idRoom', models.AutoField(primary_key=True, serialize=False)),
                ('roomNumber', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Temperature',
            fields=[
                ('idTemperature', models.AutoField(primary_key=True, serialize=False)),
                ('temperature', models.FloatField(default=0)),
                ('time', models.TimeField()),
                ('date', models.DateField()),
                ('idPatient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unodosmattress.Patient')),
            ],
        ),
        migrations.CreateModel(
            name='TemperatureEveryMinute',
            fields=[
                ('idTemperature', models.AutoField(primary_key=True, serialize=False)),
                ('temperature', models.FloatField(default=0)),
                ('time', models.TimeField()),
                ('date', models.DateField()),
                ('idPatient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unodosmattress.Patient')),
            ],
        ),
        migrations.AddField(
            model_name='news',
            name='idPatient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='unodosmattress.Patient'),
        ),
        migrations.AddField(
            model_name='heartrateeveryminute',
            name='idPatient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unodosmattress.Patient'),
        ),
        migrations.AddField(
            model_name='heartrate',
            name='idPatient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unodosmattress.Patient'),
        ),
        migrations.AddField(
            model_name='beds',
            name='idRoom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unodosmattress.Room'),
        ),
    ]
