# Generated by Django 2.1.1 on 2019-02-24 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unodosmattress', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='religion',
        ),
    ]
