# Generated by Django 2.1.1 on 2018-11-17 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('unodosmattress', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeartRatePerMinute',
            fields=[
                ('idHeartRate', models.AutoField(primary_key=True, serialize=False)),
                ('heartRate', models.FloatField(default=0)),
                ('time', models.TimeField()),
                ('date', models.DateField()),
                ('idPatient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unodosmattress.Patient')),
            ],
        ),
        migrations.CreateModel(
            name='TemperaturePerMinute',
            fields=[
                ('idTemperature', models.AutoField(primary_key=True, serialize=False)),
                ('temperature', models.FloatField(default=0)),
                ('time', models.TimeField()),
                ('date', models.DateField()),
                ('idPatient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unodosmattress.Patient')),
            ],
        ),
    ]
