# Generated by Django 2.1.7 on 2019-03-04 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unodosmattress', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient_doctors',
            old_name='Doctor',
            new_name='idDoctor',
        ),
        migrations.RenameField(
            model_name='patient_doctors',
            old_name='Patient',
            new_name='idPatient',
        ),
        migrations.RemoveField(
            model_name='patient_doctors',
            name='id',
        ),
        migrations.AddField(
            model_name='patient_doctors',
            name='idPatientDoctor',
            field=models.AutoField(default=None, primary_key=True, serialize=False),
        ),
    ]
