# Generated by Django 2.1.1 on 2019-02-24 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unodosmattress', '0002_remove_patient_religion'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='restrictions',
            field=models.CharField(default='false', max_length=20),
        ),
    ]
