# Generated by Django 2.1.1 on 2018-11-17 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unodosmattress', '0002_heartrateperminute_temperatureperminute'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HeartRatePerMinute',
            new_name='HeartRateEveryMinute',
        ),
        migrations.RenameModel(
            old_name='TemperaturePerMinute',
            new_name='TemperatureEveryMinute',
        ),
    ]
