# Generated by Django 2.1.1 on 2019-02-26 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unodosmattress', '0003_patient_restrictions'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
