# Generated by Django 2.0.5 on 2019-02-26 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unodosmattress', '0004_patient_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='count',
            new_name='countHR',
        ),
        migrations.AddField(
            model_name='patient',
            name='countT',
            field=models.IntegerField(default=0),
        ),
    ]
