# Generated by Django 2.1.1 on 2018-11-19 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('unodosmattress', '0005_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='idPatient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='unodosmattress.Patient'),
        ),
    ]
