# Generated by Django 2.1.1 on 2019-02-17 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unodosmattress', '0008_auto_20190217_2158'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='status',
            new_name='accountStatus',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='status',
            new_name='accountStatus',
        ),
    ]
