# Generated by Django 2.1.1 on 2019-02-21 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unodosmattress', '0009_auto_20190217_2201'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('idNotification', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('bedNumber', models.IntegerField()),
                ('body', models.CharField(max_length=100)),
            ],
        ),
    ]
